### ISSUE TITLE
Industrial Elevator - Call Post not working

### ISSUE THREAD

**Issue by Superfrettchen** [StrangeLoopGames/EcoSuggestions#1357] opened 2021-01-29 18:18 UTC
I build a Shaft for my new Industrial Elevator (very cool!) and placed a wooden elevator call post next to it. It worked! Now i got down into the Mine and placed the second wooden elevator call post next to the Shaft. But this second one wont work, no matter where I place it - left, right, even under the elevator does not work. (error message: "Cannot find elevator - must be placed next to elevator shaft")
Our Server has Mods installed, so my Problem could also be caused by that.

**Comment by D3nnis3n** [comment] 2021-01-29 20:39
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20158

**Closed by D3nnis3n** 2021-01-29 20:39 UTC
