### ISSUE TITLE
Paint

### ISSUE THREAD

**Issue by XerWolf** [StrangeLoopGames/EcoSuggestions#1255] opened 2020-10-11 17:04 UTC
Ability to make paint from different resources.  Blue/purple from Huckelberries.  Yellow from pineapple/corn.  Black from shale/coal,  green from fiber, orange from papaya, white from crushed limestone.  Maybe added to  Builder profession #1253

**Comment by D3nnis3n** [comment] 2020-10-12 13:59
Duplicate of #224 in conjunction with #1232

**Closed by D3nnis3n** 2020-10-12 13:59 UTC
