### ISSUE TITLE
Water Vehicles

### ISSUE THREAD

**Issue by BoatsGuy** [StrangeLoopGames/EcoSuggestions#1408] opened 2021-03-10 08:22 UTC
I've noticed much of the world is covered in water, but isn't used in many ways that are and have been integral to Earth's ecosystem. Given that commute on land is complicated by uneven terrain and rubble it would make a lot of sense to give players the ability to commute over water; first alone, and then with an increasing number of goods at greater efficiency depending on the extent of their research into certain technologies. 

Even at a relatively slow speed, the efficacy of boats for transport could open up the in-game world for more real-to-life economics and commerce.

**Comment by D3nnis3n** [comment] 2021-03-18 15:31
This is currently in the works and probably a duplicate of over 9000 suggestions so I'm closing this :D

**Closed by D3nnis3n** 2021-03-18 15:31 UTC
