### ISSUE TITLE
Economy Feature Suggestion - Auctions/Bidding for contracts and other trades

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoSuggestions#1058] opened 2020-04-22 07:22 UTC
It is often difficult to respond to changing prices, or to correctly price a contract without a lot of trial and error.

It might be helpful to be able to put an item/deed/contract up for auction or tender, so that players can bid on how much (or how little) something is worth to them.

This would make determining a price for a particular action or resource significantly easier in certain cases, and could be quite powerful. With interesting drawbacks when you mistime your auction, as well. Would require some governance and advertising and other potentially interesting things.

**Comment by D3nnis3n** [comment] 2020-04-24 09:40
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/593

**Closed by D3nnis3n** 2020-04-24 09:40 UTC

**Comment by trickenso** [comment] 2020-04-24 09:50
Ah! Thanks for this, Dennis. I thought I'd looked for an existing suggestion, but obviously not hard enough!

**Comment by D3nnis3n** [comment] 2020-04-24 10:12
Haha, i wanted this very early, even before i worked at SLG.

**Comment by trickenso** [comment] 2020-04-24 10:29
It's always a good day when I find out my 'wonderful idea' has been had by someone far cleverer, several years previously :D

**Comment by D3nnis3n** [comment] 2020-04-24 10:32
Haha, i'm not cleverer than you, i've read your posts with a lot of detail and knowledge of stuff ;)

**Comment by trickenso** [comment] 2020-04-24 13:13
😄 We can agree to disagree
