### ISSUE TITLE
[Suggestion] Minetrack and minewagons

### ISSUE THREAD

**Issue by radekkpl** [StrangeLoopGames/EcoSuggestions#1629] opened 2022-04-09 10:07 UTC
Minetrack can be made from wood (can handle only one wagon), metal (can handle two wagons), steel (can handle three wagons)

Minetrack can be steep like one block ramp and track must be ended with motor block. Can use mechanical power, or electric power (two type of wagons? Capacity?) Later on can use also elevator post buttons to summon cars to lower or upper end. Early game need to stand at upper engine block.

Maybe one wagon can be as passanger wagon.

**Comment by D3nnis3n** [comment] 2022-05-13 13:02
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1571

**Closed by D3nnis3n** 2022-05-13 13:02 UTC
