### ISSUE TITLE
[Server] Option to have world pause when last player logs out automatically

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#1002] opened 2020-04-05 12:54 UTC
When no players are actively playing the game, it makes less sense to run it aside from passive benefits like skill points going up or plants growing in real time. I have also noticed that people in general seem to join servers when it starts, grab some land, then just leave for a few days because they feel like they'd be left out otherwise.

At present, I can manually set the server to pause and then automatically unpause when someone signs in, but if I could set it to automatically pause when the last person signs out then pause when someone signs in that would encourage more activity since, with no one in the world, nothing is happening. It would also be of benefit to smaller groups that would otherwise need more active work to beat the meteor.

I'm sure some people wouldn't like this, but as a server setting I think it can really work well. 

The setting could be as simple as saying that if no players are logged in, pause. That way it's paused from the moment the server starts up until the moment someone signs in as well.

**Comment by D3nnis3n** [comment] 2020-04-19 00:32
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12660

**Closed by D3nnis3n** 2020-04-19 00:32 UTC
