### ISSUE TITLE
Add Item to Repairtable with click

### ISSUE THREAD

**Issue by TheOnlyMc** [StrangeLoopGames/EcoSuggestions#968] opened 2020-03-27 11:52 UTC
Every time i need to drag the item into the repair slot instead of just clicking it in the taskbar.

**Comment by LWChris** [comment] 2020-03-29 00:12
Especially with a small GUI, it's a bit fiddly to drag and drop.

Actually, since the table does nothing else, it would be even cooler to have a keyboard shortcut (e. g. "R" key) to repair the currently active tool while looking at the table without even having to open the table's interface. Press E to open, R to repair current tool for whatever it costs. Then you could just stand in front of the table, use the mouse wheel to scroll through the toolbar and press R when you want to repair that tool.

**Comment by D3nnis3n** [comment] 2020-04-19 00:37
Duplicate of bug https://github.com/StrangeLoopGames/EcoIssues/issues/10248

**Closed by D3nnis3n** 2020-04-19 00:37 UTC
