### ISSUE TITLE
Add admin commands to pause the clock / rewind time

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1442] opened 2021-04-08 08:31 UTC
Someone was askign about how they could pause the time or rewing the clock while they set up a server for a custom map kind of like the White Tiger. They want to modify a map and have it start at 0:00 oficially. Not sure if it would be feasible for some things (some transactions might get messed up), but it might be a neat feature for some servers that want to do things neatly.

**Comment by D3nnis3n** [comment] 2021-04-08 13:52
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1204.

Rewind of time will not be supported due to the server list being based on it and frauding it being a violation of our ToS which we do not tolerate.

**Closed by D3nnis3n** 2021-04-08 13:52 UTC
