### ISSUE TITLE
Pipes on/off valve 

### ISSUE THREAD

**Issue by extant1** [StrangeLoopGames/EcoSuggestions#554] opened 2018-09-11 14:04 UTC
Create a new pipe block with a twist valve or lever that enables or disables the flow through the pipes.

**Comment by D3nnis3n** [comment] 2021-11-26 13:19
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/63

**Closed by D3nnis3n** 2021-11-26 13:19 UTC
