### ISSUE TITLE
Sawmill will NOT output order to any Storage after removing a stockpile

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#791] opened 2019-01-04 20:12 UTC
**Version:** 0.7.8.8 beta

I built a Sawmill and placed it (**ALL** storage is linked) a friend with permission on my deed ordered Lumber, in redesigning my house i removed a stockpile and the order is just sat there waiting to be collected, all i can do is Cancel this Order, i have even tried replacing the stockpile where it was, but that doesn't work either. We **NEED** a fix that no matter who orders on your table if a storage is removed it **WILL** go to the **NEXT** Storage in list and output the order.
![snap3620](https://user-images.githubusercontent.com/29383891/50708654-0564b600-105d-11e9-803c-5616fb5aabae.png)
![snap3621](https://user-images.githubusercontent.com/29383891/50708655-0564b600-105d-11e9-9762-04b77cc78ae3.png)

what i am trying to get at is that as the Owner of the Deed whose table this is on All my Storage that is Linked should **OVERRULE** any other chosen Storage, so if that storage is removed (that another player has linked to on my deed) it WILL still Output

**Comment by D3nnis3n** [comment] 2020-12-15 11:13
Closing as working as intended.

**Closed by D3nnis3n** 2020-12-15 11:13 UTC
