### ISSUE TITLE
Elevator Suggestion!

### ISSUE THREAD

**Issue by Ciel-001** [StrangeLoopGames/EcoSuggestions#1319] opened 2020-11-29 03:06 UTC
While using the elevator is certainly helpful, it's got 1 drawback. We can't stop it at what would be considered "floors". It'd be nice if the elevator stopped at button A, B or C on the way down so it'd stop at other buttons in the chain if any were present. 

This'd help a whole lot for those that have large tall buildings or for those that have several layers to a mine/mountain they need to go down. Which in our case is the issue, having to try and stop the elevator at the right level to get your carts. large carts, trucks etc.. on and off is a pain if it ends 1 block too high or too low.

I don't really know how easy it would be to pull this off but it'd be really helpful for those that like to do big complicated builds.

**Comment by Rambo99** [comment] 2020-11-30 16:20
I agree. I myself have been dreaming about this for a long time, with only one addition - so that the elevator stops not on every floor, but on the one that the player will indicate. It can be implemented simply - since to call the elevator, players on each "floor" put "buttons to call" the elevator, then the floors can be numbered by buttons, the button in the elevator car equals the button on the floor, if the floor number specified by the player coincides with the number of the button on floor - the elevator stopped, no - drove on. That would be great, and make the 1-cube elevator wider, otherwise my "modern truck" does not fit into it.

**Comment by D3nnis3n** [comment] 2020-12-07 14:37
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/553

**Closed by D3nnis3n** 2020-12-07 14:37 UTC
