### ISSUE TITLE
You should be able to pre-signup for elections

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1462] opened 2021-04-22 23:04 UTC
Currently, elections in ECO are a bit skewed towards the first person to join them. You join first, you get some people to vote for you since you're the only person running and when someone else joins 12 hours later you have a 10 vote lead they'll never catch up to.

It would be nice if we were able to pre-signup for elections to avoid this issue. Anyone could Join an Election even before it starts with a speech and everything. Then, when someone would start the election, everyone that pre-joined the election would instantly be enrolled into the election.

This might not help with the first election, but for anything that's a reoccuring election (say, PM / DPM / senator elections on White Tiger) it would be a really nice boon to equalise the playing field.

**Comment by D3nnis3n** [comment] 2021-04-22 23:18
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1197

**Closed by D3nnis3n** 2021-04-22 23:18 UTC
