### ISSUE TITLE
[Bug] Elevator desync makes item useless 

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoSuggestions#1646] opened 2022-05-16 00:25 UTC
When using elevators they desync heavily, even just between 1 client and the server. As soon as you add more players to the mix things can become chaotic with each person seeing the elevator in a different position and vehicles being pushed around into space. I'm fairly certain the dev team are already aware of this as it's kind of hard to miss so I'm not sure what information I can give to help with further information.

**Comment by D3nnis3n** [comment] 2022-05-30 07:29
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20738

**Closed by D3nnis3n** 2022-05-30 07:29 UTC
