### ISSUE TITLE
We should be able to cancel out of tool swing animation

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1614] opened 2022-02-28 10:50 UTC
I often run around with a pickaxe while tabbing in and out of the game, as well as holding my mouse button while mining. Many times I have accidentally destroyed a floor, wall or ceiling in a mine when I didn't mean to, mostly because once the game registered the input and the animation started, I couldn't cancel out of it without switching tools. It would be nice if we let go of button mid-animation the animation would be cancelled without executing the action.

Of course you wouldn't necessarily want this for all the tools - perhaps a toggle for each tool type? I know I'd want to toggle my pickaxe, maybe the hammer, but wouldn't care so much about a shovel or an axe.

Either or, it would be nice to have some finer control over this.

**Comment by D3nnis3n** [comment] 2022-05-13 13:06
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1538

**Closed by D3nnis3n** 2022-05-13 13:06 UTC
