### ISSUE TITLE
[0.9] Give more hunting XP for headshots / more damage

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#975] opened 2020-03-30 05:59 UTC
I like the idea that headshots to animals deal more damage, but that also means that if you want to level up your hunting skills, you will receive less XP per animal if you only headshot. It would be nice to perhaps give players more XP for landing those headshots to balance things out, or maybe even giving them XP based on damage dealt. This would for example make the poor turtles less of a viable training target ;).

**Comment by D3nnis3n** [comment] 2020-04-19 01:00
Duplicate of bug https://github.com/StrangeLoopGames/EcoIssues/issues/15032

**Closed by D3nnis3n** 2020-04-19 01:00 UTC
