### ISSUE TITLE
Stockpile inputs/outputs

### ISSUE THREAD

**Issue by Sakexz** [StrangeLoopGames/EcoSuggestions#1179] opened 2020-08-12 17:52 UTC
Hello! ive been playing for a decent while, and the really big issue i have is when i do big orders i have to fill the tables manually stack by stack since all the stockpiles are full of other stuff.

So i thought of input/output only modes for storage containers, such as stockpiles. so that i can manage the storage around my areas a little bit better.

**Comment by D3nnis3n** [comment] 2020-08-17 00:31
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/654

**Closed by D3nnis3n** 2020-08-17 00:31 UTC
