### ISSUE TITLE
[0.9 Staging-1489] Let us exit forward through a ladder

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#974] opened 2020-03-30 02:48 UTC
I built a ladder on the side of my house in hopes of getting to the roof. However, when I get to the top, I can't exit it forward (onto the roof). I can only go to the sides and back:

![image](https://user-images.githubusercontent.com/964559/77870316-e9b37580-71f5-11ea-844e-a2a4b47d2407.png)

I could build the ladder facing away from the building to be able to get onto the building, but that would look silly. So it would be nice if you could pass through the ladder forward - perhaps the ladder should be an item you could move through like some bushes or the like?

**Comment by D3nnis3n** [comment] 2020-04-19 00:36
Duplicate of bug https://github.com/StrangeLoopGames/EcoIssues/issues/9908

**Closed by D3nnis3n** 2020-04-19 00:36 UTC
