### ISSUE TITLE
Implement White Tiger's skill system to address the problem of resource glut

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1271] opened 2020-10-15 06:28 UTC
Currently playing on the Coast Redwood server and it has a bit of an issue with some materials experiencing a resource glut - there are a few too many active hunters, a good portion of the population are miners, etc. This leads to a bit of an over-abundance of resources like meat, stone, ore, etc. There is also a limit to how much stuff people can buy, consume, etc. - you only need so much meat in the end.

It might be worthwhile to use the research as a form of night-endless resource sink White Tiger style. These cover about all of the professions and if you only produced research papers instead of books you would make all papers valuable through the entire run. A lot of those papers get really cheap once you have some high enough technology available anyway, so those would slow down the advancement of the skills only for so long.

I understand that on very low collab servers where everyone gets a lot of skill points this might affect people more than high collab, so perhaps it could be a toggle for the server options whether or not to use one recipe or the other.

**Comment by D3nnis3n** [comment] 2020-10-19 01:10
Hello ThePiachu,
we actually already debated this a good while back internally, but the goal for 'knowledge' in Eco is it to be free and shareable, so what White-Tiger does is something not intended by design, but only done by me for economic reasons, as i dissent to that opinion and rather have a more economic focus.

The work parties are part of this design goal where people work together to get their knowledge without economy being involved. With the expansion of that system to a more global one for research this will only get stronger. Claim Papers ultimately won't be tied to research anymore either in Towns and Nations upgrade, so Tiger will likely change this system until a point is reached in main game development where the advantage of groups in research is soo small (due to being global) that all changes to it will be removed on Tiger, as the reason we have this system on tiger is solely because the papers giving claim papers and claim papers being used as the backing item for currency.

This means this won't be implemented and hence i'm closing this issue.

**Closed by D3nnis3n** 2020-10-19 01:10 UTC

**Comment by ThePiachu** [comment] 2020-10-19 05:52
Thanks for the detailed explanation. Sounds like Towns and Nations will be an interesting shake-up to the game :) .
