### ISSUE TITLE
Being able to put a buy order on a Tag

### ISSUE THREAD

**Issue by Assimilater** [StrangeLoopGames/EcoSuggestions#1641] opened 2022-05-05 20:56 UTC
I want to buy 100 wood. I don't care if it's cedar or birch, I just need wood. Thanks for coming to my ted talk :)

**Comment by D3nnis3n** [comment] 2022-05-13 13:01
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14630

**Closed by D3nnis3n** 2022-05-13 13:01 UTC
