### ISSUE TITLE
Cargo lift and Vehicle lift

### ISSUE THREAD

**Issue by OCharnyshevich** [StrangeLoopGames/EcoSuggestions#833] opened 2019-05-26 20:32 UTC
When do you want to get gold in a tropic biome, you dip down very deeply.
After mining, you pick up the load but you only have a wooden cart with a small inventory.
I suggest adding cargo lift and vehicle lift.

![expansion](https://user-images.githubusercontent.com/4406080/58386851-69891600-800e-11e9-82b9-9f4dcc3f725b.jpg)
![2-5-1](https://user-images.githubusercontent.com/4406080/58386852-69891600-800e-11e9-871e-19386d274aa7.jpg)
![a17a0be10a8c18f9718a2a32a1c5c0ba](https://user-images.githubusercontent.com/4406080/58386853-6a21ac80-800e-11e9-8315-b65bb2363311.jpg)

**Comment by D3nnis3n** [comment] 2021-11-26 13:31
We got an industrial elevator for vehicles now, a cargo lift would be a duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/327

**Closed by D3nnis3n** 2021-11-26 13:31 UTC
