### ISSUE TITLE
warehouse production management

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoSuggestions#1187] opened 2020-08-19 13:50 UTC
i know that you can select a stockpile link/unlink

what would be nice is to have stockpile A be input, and Stockpile B be output
meaning no overflow into stockpile A when stockpile B is full

**Comment by D3nnis3n** [comment] 2020-08-24 15:49
Duplicate of #654

**Closed by D3nnis3n** 2020-08-24 15:49 UTC
