### ISSUE TITLE
Make Stores able to purchase by tag

### ISSUE THREAD

**Issue by 99thGamer9** [StrangeLoopGames/EcoSuggestions#1560] opened 2021-10-27 16:17 UTC
I would like to have the option to buy tags instead of specific items, so that you don't have to add all manually and also have a purchase limit for all of them together

**Comment by Dave247** [comment] 2021-11-18 03:35
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14630

**Comment by D3nnis3n** [comment] 2021-11-26 11:17
Closed due to being a duplicate.

**Closed by D3nnis3n** 2021-11-26 11:17 UTC
