### ISSUE TITLE
Suggestion: Multiple Module/Upgrade Inputs on Tables

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoSuggestions#1245] opened 2020-10-07 15:06 UTC
I suggest that for tables which can accept multiple specialty Upgrades, that there be multiple slots or some sort of ability to select an upgrade to be applicable. For some of the advanced tables, where the labor can be electronics, oil drilling, industrial, etc., crafting some items in the most efficient manner means constantly switching the upgrades. For example, if making basic circuits most efficiently, I would need the oil drilling upgrade to craft fiberglass then electronics to craft the other components. Adding more slots would be a nice QoL improvement.

**Comment by D3nnis3n** [comment] 2020-10-12 14:43
The intention behind that system is that you create multiple factory lines with multiple different tables to do this. You can of course switch modules if you want to, but then it not being as comfy as having multiple tables is intended.

Given this works as intended and has no chance to be changed currently, i'm closing this issue.

**Closed by D3nnis3n** 2020-10-12 14:43 UTC
