### ISSUE TITLE
Stockpile Filters

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoSuggestions#1236] opened 2020-10-02 23:07 UTC
It would be useful for more complex builds to be able to set a filter of what can automatically go into stockpiles from buildings.

**Comment by IdkIjustwantedtosuggestsomething** [comment] 2020-10-03 00:13
This has already been mentioned. Go vote for it (thumbs up) on that thread :)
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/654

**Comment by D3nnis3n** [comment] 2020-10-12 13:47
Duplicate of #654

**Closed by D3nnis3n** 2020-10-12 13:47 UTC
