### ISSUE TITLE
Grouping recipes

### ISSUE THREAD

**Issue by Icycube2k** [StrangeLoopGames/EcoSuggestions#1272] opened 2020-10-15 11:47 UTC
Each workstation has plenty of recipes to craft. Some are quite similar (e.g. salads for chefs or different types of hewn logs or lumber). Instead of just listing all possible recipes at a work station, it would be better if similar recipes are grouped together (similar to file folders or listed menus) to faster find the recipe you are currently looking for.  Just as in the storage section where you can open/close specific containers, the recipe menu could be handled similarly.

**Comment by ThePiachu** [comment] 2020-10-15 21:10
Yup, would be great!
#1251

**Comment by D3nnis3n** [comment] 2020-10-19 01:01
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1251

**Closed by D3nnis3n** 2020-10-19 01:01 UTC
