### ISSUE TITLE
(Suggestion) Plant Growth Rate Variable for Single Player

### ISSUE THREAD

**Issue by RaptorX23YT** [StrangeLoopGames/EcoSuggestions#1299] opened 2020-11-11 14:49 UTC
Can the growthmaturitydays Variable be set to multiply by a variable that can then be exposed for single player worlds like the other settings when setting up a single player world. This way, a single, or low colab world can be set up with custom or reduced growth times without having to get into the config files for every single plant that they might want to grow faster. Simply have a Plant Growth multiplier, so that a person can set plant growth time to 0.1, and still be able to harvest plants in 2.4 to 5 hours, instead of several days. Another one could be set for trees if a different variable is desired for those, or make them a factor of the plant growth variable

**Comment by D3nnis3n** [comment] 2020-11-16 09:49
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19166

**Closed by D3nnis3n** 2020-11-16 09:49 UTC
