### ISSUE TITLE
Allow copying of online servers for offline play

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#983] opened 2020-03-30 21:20 UTC
As a player that wants to learn some cool building design or what have you, I'd love to explore what people have built on the various online servers. However, since a lot of those locations are locked, I don't have a way to do that easily. It would be nice if there was a way to download the online server map and be able to play it offline, with all the debug tools to get into places you couldn't before. It would also be a way for people to archive servers they've played on before they are taken down, etc.

**Comment by redwyre** [comment] 2020-03-31 15:25
This is unlikely, as it would put extra load on the server, as well as allow cheating (download map, play locally with admin to find where resources are, go back to online server and claim resources). Some servers make the map available after they restart, if you want a a copy of a particular server you'll have to talk to the owner.

**Comment by johnkslg** [comment] 2020-03-31 16:19
Could be an opt-in feature for servers to allow download.  
I do like the idea of an Eco metaverse where you can visit other worlds...

**Comment by Elliander** [comment] 2020-04-02 03:48
I've brought up a similar idea in the past when a server I liked shut down, but redwyre brings up a good point - it would put extra load on the server.

Maybe the server could have an extra option where the server host can input google drive credentials to have backups uploaded to periodically (which is actually not a bad idea for preservation in case of total drive failure) and an option to make a download link made available to others the way Discord links are.

**Comment by mirasrael** [comment] 2020-04-02 05:39
@Elliander you can currently configure to use S3 storage for backups.

**Comment by Elliander** [comment] 2020-04-03 10:51
That's good to know, but as far as I know Amazon S3 is paid only, whereas Google has free tiers, right? I'm already paying for my Google Drive, plus domain hosting, so I'd rather not pay for yet another service. If "cloud" storage (I always hated that term) is implemented for one service though, I'm guessing it can be implemented for others.

For those reading this who may want to use Amazon S3 though, can you point to documentation about that? Because I've never seen that setting.

**Comment by D3nnis3n** [comment] 2020-04-19 00:24
As a server hoster i do not want that anyone can just copy my map that i put my hard work in without my permission, using my resources. I'd not opt-in either. I do publish the worlds by free will after the cycle is over though, so people can play on with the hard stuff they made.

I've seen a lot of copycats in Minecraft that just used my work via the possibilitites to copy worlds there via mods and i really didn't like it. A opt-in is fine, if it's off by default. But i'd guess pretty much noone would activate it, making it a rather useless feature.

**Comment by D3nnis3n** [comment] 2021-11-26 13:50
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/122

**Closed by D3nnis3n** 2021-11-26 13:50 UTC
