### ISSUE TITLE
Asphalt Roads: Two Minor But Much Needed Improvements

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#1216] opened 2020-09-21 01:15 UTC
I love the new asphalt roads, they are everything I have ever hoped for. However there are two minor things which I would love to see added to them:
1. An alternate yellow version added to the road stripes set. This would allow for perfect replication of real life roads.
2. A set of both dashed and solid stripes that are half the normal width and centered on the block's very edge. Right now stripes are centered in the middle of the block, forcing symmetrical roads to use an odd width. With the aforementioned set, you could put two of the blocks together to form a full width road stripe centered on the edge of the two blocks, allowing for even width roads. Since most two lane roads are centered on two plots (aka 8-10 wide), this addition would make symmetry way easier.

Two illustrated examples are linked below:
https://imgur.com/HxYR3BB
https://imgur.com/xMuzjTn

**Comment by D3nnis3n** [comment] 2020-10-12 13:34
Hello Blanclour,
1) is specific to some countries, my country has no yellow stripes for example.
2) is part of this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/17408

I don't see us implementing yellow stripes in the near future, hence i'm closing this issue for the time being, as the other part of the issue is already on the bug tracker.

**Closed by D3nnis3n** 2020-10-12 13:34 UTC
