### ISSUE TITLE
Allow users to opt out of profanity filter

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1431] opened 2021-04-01 23:50 UTC
While the profanity filter is neat for limiting the amount of bad language people use, as someone that's not bothered by these thigns it might be nice to have an option to opt out of the profanity filters and see the little bit of cuss rather than the censoring dots. This might still make the profanity filter effective while annoying people that prefer seeing cuss over censoring a little bit less ;).

**Comment by D3nnis3n** [comment] 2021-04-08 14:14
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/2

**Closed by D3nnis3n** 2021-04-08 14:14 UTC
