### ISSUE TITLE
[Suggestion] See Districts Visually in Game

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#772] opened 2019-04-08 16:42 UTC
Currently, districts can only be seen visually in the web browser. In game we can only see them as text in the lower right hand part of the screen that only shows when we are in the district. It would be nice if there was a world map option to visualize districts in the same way land claims are visualized. This could be combined with the already existing function to overlay world map layers onto the actual terrain to more easily see districts and plan accordingly.

**Comment by D3nnis3n** [comment] 2019-04-08 19:49
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/601

**Closed by D3nnis3n** 2019-04-08 19:49 UTC
