### ISSUE TITLE
better configurable Law Timers

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoSuggestions#1420] opened 2021-03-25 18:12 UTC
right now, when using a law that triggers on a timer, e.g. a Global Timer or a Citizen Timer, the time when a law triggers is impacted by the time a law went into effect, it resets whenever a law is changed by election and it is depending on civics ticks.
It would be great to have the option to set timers to specific server times, e.g. "every server day at 00:00", or even real times "every day at 00:00 CET", though real times would mean that server downtime leads to lost time ingame.
This seems to be achievable right now through checking the world age every time a timer triggers on a short cooldown, but it is cumbersome and makes writing the law even more complicated.

**Comment by D3nnis3n** [comment] 2021-05-19 23:47
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/872

**Closed by D3nnis3n** 2021-05-19 23:47 UTC
