### ISSUE TITLE
Automatic connection of new storages to existing devices

### ISSUE THREAD

**Issue by yalokcin** [StrangeLoopGames/EcoSuggestions#863] opened 2019-07-21 10:10 UTC
I consider it a big problem and a bug to automatically connect new storages to already existing devices! This leads to uncontrolled unloading of the products produced in them. As well as a complete violation of custom logic in devices. The only additional storage makes running bulging eyes and check what devices could reach him. Is this the point of the game? Make the new repository inactive by default for everyone. I will connect the necessary storage to the necessary device !!!

**Comment by D3nnis3n** [comment] 2021-11-26 13:35
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/123

**Closed by D3nnis3n** 2021-11-26 13:35 UTC
