### ISSUE TITLE
electric motors

### ISSUE THREAD

**Issue by sossololpipi** [StrangeLoopGames/EcoSuggestions#1652] opened 2022-06-21 14:06 UTC
despite advances in technology, people doing milling or other such professions are stuck with old-school windmills & waterwheels for mechanical energy. perhaps an electric motor of some sort could assist these professions as the world progresses beyond these simple sources of power.

**Comment by D3nnis3n** [comment] 2022-06-28 08:15
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/1045

**Closed by D3nnis3n** 2022-06-28 08:15 UTC
