### ISSUE TITLE
SUGGESTION: Law Managment

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#583] opened 2018-09-17 19:04 UTC
_From @CobaltEcho on September 15, 2018 15:55_

It would be great if there was a way to Save/Load or Import/Export laws.  They don't even have to be "completed" laws, but when you "load" them, it has the law completed so you can make small changes and then submit.  It really sucks when you make a really complicated law and find a small error, then you have to start all over.  Or when you start a new world and everyone has laws they like, but you have to spend hours and hours recreating them (and hope you dont make a small error!).

_Copied from original issue: StrangeLoopGames/EcoIssues#9381_

**Comment by MarjieAVolk** [comment] 2018-09-17 19:06
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4090

**Closed by MarjieAVolk** 2018-09-17 19:06 UTC
Labels: Suggestion
