### ISSUE TITLE
Add more authorizations to claimed areas

### ISSUE THREAD

**Issue by xKingPanda** [StrangeLoopGames/EcoSuggestions#1226] opened 2020-09-27 17:43 UTC
For example, we constantly run into the problem of having to give people FULL access to everything and we want to say just give them the ability to hunt or dig within the area without having to make a contract

**Comment by Engimage** [comment] 2020-09-30 10:24
Hunting in particular should be globally addressed. There is a workaround using laws but it is honestly too complex.
I guess hunting should be made public by default and only optionally limited by claims.

Also often there is a sitiation where farmers claim surface, or just for a building. But still want to allow miners to dig below surface. So it makes sense to have more extensive permission settings.

**Comment by D3nnis3n** [comment] 2020-10-12 14:04
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/594

**Closed by D3nnis3n** 2020-10-12 14:04 UTC
