### ISSUE TITLE
SUGGESTION: Deactivate autolinking

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#246] opened 2018-05-30 18:11 UTC
_From @Thyriel on February 19, 2018 19:2_

It would be really helpfull later if there would be a way to deactivate new chests etc. being automatically linked with everything when placed. (at best as an option at crafting stations etc.)
I have a lot of crafting stuff in my house that only have certain chests linked so the crafted stuff gets sorted automatically but it becomes really tedious that i have to deactivate the link for every new placed chest on 8+ crafting stations manually each time

_Copied from original issue: StrangeLoopGames/EcoIssues#4831_

**Comment by BlazeGuy2** [comment] 2018-05-30 18:11
_From @metachronism on March 16, 2018 18:40_

seems like most a UI design issue - I agree we need easier ways to manage the lists when it becomes larger

**Comment by BlazeGuy2** [comment] 2018-05-30 18:11
_From @Thyriel on March 16, 2018 18:49_

Being able to define a strict output chest/stockpile (multiple so things like lumber still work) would be great too btw ;)

**Comment by D3nnis3n** [comment] 2021-11-26 12:29
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/123

**Closed by D3nnis3n** 2021-11-26 12:29 UTC
